### ISSUE TITLE
[ Compatibility Issue ] Not fully compatible with any element which is holding data in v-for

### ISSUE THREAD

**Issue by polarove** [vueuse/motion#107]
In template:
![code](https://user-images.githubusercontent.com/95893742/229254635-af604b5e-cd31-4758-9261-d0f4d52256fa.png)

In script setup
![cod2e](https://user-images.githubusercontent.com/95893742/229254610-4e59e784-3afb-4b14-871b-4048d025031f.png)

What I expected:
An element will scale down when mouse hovering, instead of each, not even an error

What it acts in actual
![捕获](https://user-images.githubusercontent.com/95893742/229254861-89c91ab8-d219-4cd8-8de8-c913e39b744f.PNG)

This action will not work as it's expected to be, and in most case, it will throw an error and says xxx is not defined.

Apparently, the variable  'target' is a array in actual.
Could you please fix it? I'd appreciate your effort!

**Comment by BobbieGoede** [comment]
As you have noticed, since you're using `ref="target"` in a `v-for` the variable will be filled with an array of elements, not a single element, since `useElementTransform` expects a single element ref it will throw an error.

I suppose it would be nice if there was a composable (maybe `useElementTransforms` or something) that would work with array refs. Not entirely sure how its usage would look like.

Also, your example code is incomplete, even if `useElementTransform` accepted an array of elements, with no further changes (I'm assuming you're using the same function for a hover or something) all elements would have changed in size instead of just one. So I'll need a better reproduction to help you with this issue.
