### ISSUE TITLE
src/features/lifeCycleHooks.ts watch(() => target) whether there is a BUG?

### ISSUE THREAD

**Issue by Mr-LJQ** [vueuse/motion#147]
target may be ref, should it be written in the form of unref(target)?
Then filter out newValue === null in the callbakc?

**Comment by BobbieGoede** [comment]
@cpreston321 
Yes I think we can convert some of these issues to discussions but it's a bit tricky for issues like this one, I'm not sure if this issue is a question or a bug report.. 🤔

In this case I tag it `needs production`, if it's a question the author will hopefully let us know, if it's a bug hopefully we get a reproduction, and if there's inactivity it will be closed automatically after 7 days due to the tag.

If converting to discussion has your preference we could do that instead for ambiguous issues like this 😄

**Comment by BobbieGoede** [comment]
This issue was closed because it was open for 7 days without a reproduction.
