### ISSUE TITLE
Can't resolve defu in @vueuse/motion/dist/index.mjs

### ISSUE THREAD

**Issue by mikael-j-rich** [vueuse/motion#166]
The dependency "defu" does not seem to get installed. Where is this coming from?

**Comment by wuhaohuang** [comment]
same problem + 1

**Comment by aquarius-wing** [comment]
I solved it by execute the shell below
```
npm install defu
```
or
```
yarn add defu
```

**Comment by BobbieGoede** [comment]
I'm unable to reproduce this using the latest release so I'm closing this, if you're still experiencing this after updating please open a new issue with a reproduction.

**Comment by NoelDeMartin** [comment]
@BobbieGoede I'm facing this issue as well, but I don't have a minimal example that I can share.

Before trying to have a minimal example, though, I wonder why `defu` is not declared as a dependency in the package.json? It [seems to be used](https://github.com/vueuse/motion/blob/main/src/directive/index.ts#L2) in the main functionality, so if this isn't happening in some project it must be because another dependency happens to use it as well.

PS: In case you want the "non minimal" example, it's this repo: https://github.com/noeldemartin/umai

**Comment by jerrybendy** [comment]
Same issue to me. I use v2 in my project. There is `defu` as dependency but not in `package.json`. I noticed that the latest version has `defu` in `package.json`, it's better to add it in v2 too.
