### ISSUE TITLE
Repository maintainer status

### ISSUE THREAD

**Issue by BobbieGoede** [vueuse/motion#168]
@Tahul @cpreston321 
Is this project still being maintained? The last release was in May last year, but has been partly broken for Nuxt projects when following the installation documentation. Although a fix (https://github.com/vueuse/motion/issues/131) for this was merged some time ago, there hasn't been a new release to include it.

I would be happy to assist with triaging and fixing issues as well as publishing releases. It's unfortunate to see this project become unmaintained, let me know if I can be of any help!

**Comment by rylanharper** [comment]
This is one of my favorite libraries within the Nuxt and Vueuse ecosystem. Would love to see further support if possible as well. It's just some small fixes away from being amazing!

**Comment by cpreston321** [comment]
Hey @BobbieGoede! Sorry for the late response. We wanted to re-write the library to have better support for tree-shaking and maintainability. I was starting on #135 last year to get it off the ground as I was in the same state as you. I was an earlier adopter to Nuxt 3 and really loved the library. 

## Backstory

Unfortunately @Tahul was experiencing a code burnout in general - maintaining  & supporting different libraries at the time. He had a a full time job. 

Also not to mention I was having a kid at the end of November last year so the free time I had was completely gone trying to take care of her and support her. Also not to mention helping support [UNJS](https://github.com/unjs),  [Clack.cc](github.com/natemoo-re/clack/), **VueUse/Motion** and my own OS Projects 😅. I think I took to much then I could handle. Lack of a better word was over working myself in the first full year in OS and was beginning to feel that same pressure as other maintainers.

While things are slowly getting better. I would love to re-vive this project and have additional hands that makes it a lot easier to maintain an OS Project! 

---

Furthermore, I would love to gather a roadmap with a good idea on what we want to do! So that others can help where they can. Again I apologize for the lack of communication on this project.

Thanks,
CP

**Comment by BobbieGoede** [comment]
Hey @cpreston321, congrats on becoming a parent 😄 it's totally understandable that providing for your family takes priority! Even though I have primarily been contributing to just one OS project ([@nuxtjs/i18n](https://github.com/nuxt-modules/i18n)) so far, I can imagine it can get stressful quick when working on several projects at once. 

>I hope that makes since, but while things are slowly getting better at home and work. I would love to re-vive this project and have additional hands that makes it a lot easier to maintain an OS Project!

>But again Taul - wanted to fully re-write the library for better support tree-shaking and SSR which was the goal last year.

I'm glad to hear that you're up for reviving this project! I can see how better tree-shaking and SSR support can be a good goal, but wouldn't it be preferable to work towards this incrementally (if possible)? 

>Furthermore, I would love to gather a roadmap with a good idea on what we want to do! So that others can help where they can.

That sounds good, I think it would be a good start to triage/label the issues to get an idea of whether most issues are bugs or feature requests (or stale) 😅. I would be happy to go through them sometime but would need permissions to add labels.

I also opened a tiny PR which fixes the failing CI actions (https://github.com/vueuse/motion/pull/167), and if you publish a new release this issue (https://github.com/vueuse/motion/issues/162) can be closed.

**Comment by Tahul** [comment]
Hey @BobbieGoede ;

is there any way I can reach you out on Discord maybe?

thank you so much for your interest in the project, it has just been a bit hard for me to keep an eye here lately.

**Comment by BobbieGoede** [comment]
>is there any way I can reach you out on Discord maybe?

Hey @Tahul, I'm `bobbiegoede` on Discord 😄 I'll send you a DM!

**Comment by BobbieGoede** [comment]
Now that there's been a new release and some issues have been resolved (and I've been invited to collaborate 💪😂🎉) I'll close this.

I won't always be as active but I'll try my best to help maintain this project and hopefully give you guys some breathing space! 😄
